[package]
name = "single-file-btree"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Krause <thomaskrause@posteo.de>"]
license = "Apache-2.0"


[dependencies]
memmap2 = "0.5"
thiserror = "1"
tempfile = "3.1"
serde = "1"
serde_derive = "1"
packed_struct = "0.10"