name: Automated tests
on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]
jobs:
  test_linux:
    name: Execute automated tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v1.3.0
      - run: cargo build --all-features --verbose
      - run: cargo test --all-features --verbose